
tab_spaces = 2
blank_lines_upper_bound = 3
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20

newline_style = "Unix"
binop_separator = "Back"
brace_style = "PreferSameLine"
# match_arm_leading_pipes = "Always"
imports_layout = "HorizontalVertical"

fn_single_line = true
reorder_impl_items = true
remove_nested_parens = true
overflow_delimited_expr = true
use_field_init_shorthand = true
format_code_in_doc_comments = true
